development:
  adapter: postgresql
  database: codevelop_development

test:
  adapter: postgresql
  database: codevelop_test

production:
    adapter: postgresql
    database: <%= ENV['DATABASE_URL'] %>
